// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Choice struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewChoice struct {
	Name string `json:"name"`
}

type NewPoll struct {
	Text    string       `json:"text"`
	Email   string       `json:"email"`
	Choises []*NewChoice `json:"choises"`
}

type NewPost struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type Poll struct {
	ID      string        `json:"id"`
	Email   string        `json:"email"`
	Text    string        `json:"text"`
	Choises []*Choice     `json:"choises"`
	Results []*PollResult `json:"results"`
}

type PollResult struct {
	Choiceid string `json:"choiceid"`
	Email    string `json:"email"`
}

type Post struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

type UpdatedPost struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

type UserChoice struct {
	PollID    string `json:"pollId"`
	ChoiceID  string `json:"choiceId"`
	UserEmail string `json:"userEmail"`
}
