// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Choice struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewChoice struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewPoll struct {
	Text      string       `json:"text"`
	UserEmail string       `json:"userEmail"`
	Choises   []*NewChoice `json:"choises"`
}

type Poll struct {
	ID        string        `json:"id"`
	UserEmail string        `json:"userEmail"`
	Text      string        `json:"text"`
	Choises   []*Choice     `json:"choises"`
	Results   []*PollResult `json:"results"`
}

type PollResult struct {
	ChoiceID  string `json:"choiceId"`
	UserEmail string `json:"userEmail"`
}

type UserChoice struct {
	PollID    string `json:"pollId"`
	ChoiceID  string `json:"choiceId"`
	UserEmail string `json:"userEmail"`
}
